### ISSUE TITLE
using  kurento-room-client in android post issue:java.lang.NoSuchMethodError: No virtual method setEndpointIdentificationAlgorithm

### ISSUE THREAD

**Issue by dhcn** [Kurento/bugtracker#104]
07-20 16:47:51.652 7492-7492/demo.webrtc.ab.com.webrtckurento E/AndroidRuntime: FATAL EXCEPTION: main
Process: demo.webrtc.ab.com.webrtckurento, PID: 7492
java.lang.NoSuchMethodError: No virtual method setEndpointIdentificationAlgorithm(Ljava/lang/String;)V in class Ljavax/net/ssl/SSLParameters; or its super classes (declaration of 'javax.net.ssl.SSLParameters' appears in /system/framework/core-libart.jar)
    at org.eclipse.jetty.util.ssl.SslContextFactory.customize(Unknown)
    at org.eclipse.jetty.util.ssl.SslContextFactory.newSSLEngine(Unknown)
    at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(Unknown)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(Unknown)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(Unknown)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(Unknown)
    at org.eclipse.jetty.websocket.client.WebSocketClient.doStart(Unknown)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(Unknown)
    at org.kurento.jsonrpc.client.JsonRpcClientWebSocket.connectNativeClient(Unknown)
    at org.kurento.jsonrpc.client.AbstractJsonRpcClientWebSocket.internalConnectIfNecessary(Unknown)
    at org.kurento.jsonrpc.client.AbstractJsonRpcClientWebSocket.connectIfNecessary(Unknown)
    at org.kurento.jsonrpc.client.AbstractJsonRpcClientWebSocket.internalSendRequestWebSocket(Unknown)
    at org.kurento.jsonrpc.client.AbstractJsonRpcClientWebSocket$1.internalSendRequest(Unknown)
    at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendRequest(Unknown)
    at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendRequest(Unknown)
    at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendRequest(Unknown)
    at org.kurento.jsonrpc.client.JsonRpcClient.sendRequest(Unknown)
    at org.kurento.room.client.KurentoRoomClient.joinRoom(Unknown)
    at demo.webrtc.ab.com.webrtckurento.MainActivity.onClick(MainActivity.java:51)
    at android.view.View.performClick(View.java:4811)
    at android.view.View$PerformClick.run(View.java:20136)
    at android.os.Handler.handleCallback(Handler.java:815)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loop(Looper.java:194)
    at android.app.ActivityThread.main(ActivityThread.java:5546)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

**KMS Version**:

Paste output of `kurento-media-server -v` in the machine where KMS is running

**Other libraries versions**:

Paste output of executing `dpkg -l | egrep -i "kurento|gst.*1.5|nice"` in the
machine where KMS is running

**Client libraries**
- Language: <Java, Node.js, JavaScript, homebrewed>
- Version:

**Browsers tested**
  Add OK or FAIL, along with the version, after browsers where you
have tested this issue:
- Chrome:
- Firefox:
- Native:

**System description:**
    Please describe your setup (where is KMS located, where are the
    clients, STUN, TURN...)

**What steps will reproduce the problem?**
1.
2.
3.

**What is the expected result?**

**What happens instead?**

**Does it happen with one of the tutorials?**

**Please provide any additional information below.**

**Comment by igracia** [comment]
The [method](https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLParameters.html#setEndpointIdentificationAlgorithm(java.lang.String)) it's looking for was added in Java 7. Can you check which JDK version you are using, and make sure that it is at least 1.7?
