### ISSUE TITLE
kurento-client-js: reconnect tests failed

### ISSUE THREAD

**Issue by pahaz** [Kurento/bugtracker#156]
**KMS Version**:

	root@tpahaz:/# kurento-media-server -v
	0:00:00.021514947    62      0x1889810 INFO    KurentoModuleManager ModuleManager.cpp:156:loadModules: Looking for modules in /usr/lib/x86_64-linux-gnu/kurento/modules
	0:00:00.022679735    62      0x1889810 DEBUG   KurentoModuleManager ModuleManager.cpp:89:loadModule: Module loaded from /usr/lib/x86_64-linux-gnu/kurento/modules/libkmscoremodule.so
	0:00:00.022785936    62      0x1889810 INFO    KurentoModuleManager ModuleManager.cpp:135:loadModule: Loaded core version 6.6.1 generated at Sep 30 2016 11:10:44
	0:00:00.023672815    62      0x1889810 DEBUG   KurentoModuleManager ModuleManager.cpp:89:loadModule: Module loaded from /usr/lib/x86_64-linux-gnu/kurento/modules/libkmsplatedetectormodule.so
	0:00:00.023758722    62      0x1889810 INFO    KurentoModuleManager ModuleManager.cpp:135:loadModule: Loaded platedetector version 6.6.0 generated at Sep 10 2016 06:57:40
	0:00:00.029384177    62      0x1889810 DEBUG   KurentoModuleManager ModuleManager.cpp:89:loadModule: Module loaded from /usr/lib/x86_64-linux-gnu/kurento/modules/libkmselementsmodule.so
	0:00:00.029562957    62      0x1889810 INFO    KurentoModuleManager ModuleManager.cpp:135:loadModule: Loaded elements version 6.6.1 generated at Sep 30 2016 12:31:04
	0:00:00.030883687    62      0x1889810 DEBUG   KurentoModuleManager ModuleManager.cpp:89:loadModule: Module loaded from /usr/lib/x86_64-linux-gnu/kurento/modules/libkmsfiltersmodule.so
	0:00:00.030975478    62      0x1889810 INFO    KurentoModuleManager ModuleManager.cpp:135:loadModule: Loaded filters version 6.6.1 generated at Sep 30 2016 13:13:48
	0:00:00.031905552    62      0x1889810 DEBUG   KurentoModuleManager ModuleManager.cpp:89:loadModule: Module loaded from /usr/lib/x86_64-linux-gnu/kurento/modules/libkmscrowddetectormodule.so
	0:00:00.031993092    62      0x1889810 INFO    KurentoModuleManager ModuleManager.cpp:135:loadModule: Loaded crowddetector version 6.6.0 generated at Sep 10 2016 07:01:16
	0:00:00.032844810    62      0x1889810 DEBUG   KurentoModuleManager ModuleManager.cpp:89:loadModule: Module loaded from /usr/lib/x86_64-linux-gnu/kurento/modules/libkmspointerdetectormodule.so
	0:00:00.032927876    62      0x1889810 INFO    KurentoModuleManager ModuleManager.cpp:135:loadModule: Loaded pointerdetector version 6.6.0 generated at Sep 10 2016 06:58:49
	0:00:00.033688234    62      0x1889810 DEBUG   KurentoModuleManager ModuleManager.cpp:89:loadModule: Module loaded from /usr/lib/x86_64-linux-gnu/kurento/modules/libkmschromamodule.so
	0:00:00.033813532    62      0x1889810 INFO    KurentoModuleManager ModuleManager.cpp:135:loadModule: Loaded chroma version 6.6.0 generated at Sep 10 2016 06:55:38
	Version: 6.6.1
	Found modules:
		Module: 'chroma' version '6.6.0'
		Module: 'core' version '6.6.1'
		Module: 'crowddetector' version '6.6.0'
		Module: 'elements' version '6.6.1'
		Module: 'filters' version '6.6.1'
		Module: 'platedetector' version '6.6.0'
		Module: 'pointerdetector' version '6.6.0'

**Other libraries versions**:

	root@tpahaz:/# dpkg -l | egrep -i "kurento|gst.*1.5|nice"
	ii  gstreamer1.5-libav:amd64             1.8.2.1~20160909143244.96.g493eee4.trusty  amd64        libav plugin for GStreamer
	ii  gstreamer1.5-nice:amd64              0.1.13.1~20160930090742.81.geebfdab.trusty amd64        ICE library (GStreamer plugin)
	ii  gstreamer1.5-plugins-bad:amd64       1.8.1.1~20160909144557.99.gf836e53.trusty  amd64        GStreamer plugins from the "bad" set
	ii  gstreamer1.5-plugins-base:amd64      1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer plugins from the "base" set
	ii  gstreamer1.5-plugins-good:amd64      1.8.1.1~20160909143047.112.g9ee4248.trusty amd64        GStreamer plugins from the "good" set
	ii  gstreamer1.5-plugins-ugly:amd64      1.8.1.1~20160909192513.89.g2685b0f.trusty  amd64        GStreamer plugins from the "ugly" set
	ii  gstreamer1.5-pulseaudio:amd64        1.8.1.1~20160909143047.112.g9ee4248.trusty amd64        GStreamer plugin for PulseAudio
	ii  gstreamer1.5-x:amd64                 1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer plugins for X11 and Pango
	ii  kms-chroma-6.0                       6.6.0.20160910065442.trusty                amd64        Kurento Chroma Filter
	ii  kms-core-6.0                         6.6.1.20160930110533.trusty                amd64        Kurento core module
	ii  kms-crowddetector-6.0                6.6.0.20160910065950.trusty                amd64        Kurento Crowd Detector Filter
	ii  kms-elements-6.0                     6.6.1.20160930122545.trusty                amd64        Kurento elements module
	ii  kms-filters-6.0                      6.6.1.20160930131150.trusty                amd64        Kurento filters module
	ii  kms-jsonrpc-1.0                      1.1.2.20160930094018.trusty                amd64        Kurento jsonrpc library
	ii  kms-platedetector-6.0                6.6.0.20160910065620.trusty                amd64        Kurento Plate Detector Filter
	ii  kms-pointerdetector-6.0              6.6.0.20160910065720.trusty                amd64        Kurento Pointer Detector Filter
	ii  kmsjsoncpp                           1.6.3~20160909143252.40.gd78deb7.trusty    amd64        Kurento jsoncpp library
	ii  kurento-media-server-6.0             6.6.1.20160930143513.trusty                amd64        Kurento Media Server
	ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.1.1~20160909144557.99.gf836e53.trusty  amd64        GStreamer development files for libraries from the "bad" set
	ii  libgstreamer-plugins-base1.5-0:amd64 1.8.1.1~20160909142623.55.g7b19cfd.trusty  amd64        GStreamer libraries from the "base" set
	ii  libgstreamer1.5-0:amd64              1.8.1.1~20160909144007.170.g0d6031b.trusty amd64        Core GStreamer libraries and elements
	ii  libnice10:amd64                      0.1.13.1~20160930090742.81.geebfdab.trusty amd64        ICE library (shared library)

**What steps will reproduce the problem?**
1. git clone https://github.com/Kurento/kurento-client-js
2. cd kurento-client-js/ && npm i
3. ./node_modules/.bin/qunit-cli -c kurentoClient:. -c wock:node_modules/wock -c test/_common.js -c test/_proxy.js test/*.js --ws_uri=ws://kms:8888/kurento

**What happens instead?**

case 1: fierwall drop packages

	root@tpahaz:/kurento-node/kurento-client-js# ./node_modules/.bin/qunit-cli -c kurentoClient:. -c wock:node_modules/wock -c test/_common.js -c test/_proxy.js test/*.js --ws_uri=ws://kms:8888/kurento

	undefinedMediaObjectCreator
	Unknown type ' { type: 'dummyUnknownType' } ', using MediaObject instead
	  ✔ Get unknown constructor

	ServerManager
	  ✖ Server manager getInfo with callback
	    Test timed out
	    null != undefined
	    Test timed out
	    null != undefined
	    Expected 1 assertions, but 2 were run
	    null != undefined
	  ✖ Server manager getInfo with promise
	    Test timed out
	    null != undefined
	    Test timed out
	    null != undefined
	    Expected 1 assertions, but 2 were run
	    null != undefined
	  ✖ Server manager getPipelines with promise
	    Test timed out
	    null != undefined
	    Test timed out
	    null != undefined
	    Expected 1 assertions, but 2 were run
	    null != undefined
	  ✖ Server manager getPipelines with callback
	    Test timed out
	    null != undefined
	    Test timed out
	    null != undefined
	    Expected 1 assertions, but 2 were run
	    null != undefined

	reconnect
	  ✖ Continue after network error
	    Test timed out
	    null != undefined
	    Died on test #3     at Object.<anonymous> (/kurento-node/kurento-client-js/test/reconnect.js:66:7)
	    at Module._compile (module.js:541:32)
	    at Object.Module._extensions..js (module.js:550:10)
	    at Module.load (module.js:458:32)
	    at tryModuleLoad (module.js:417:12)
	    at Function.Module._load (module.js:409:3)
	    at Module.require (module.js:468:17): Cannot read property 'create' of undefined
	    null != undefined
	    Expected 13 assertions, but 3 were run
	    null != undefined

	waiting
	reconnect to server 0 100 undefined
	/kurento-node/kurento-client-js/test/waiting.js:79
	    client.getMediaobjectById(pipeline.id, function (error, pipeline_) {
	                                      ^

	TypeError: Cannot read property 'id' of undefined
	    at Timeout._onTimeout (/kurento-node/kurento-client-js/test/waiting.js:79:39)
	    at tryOnTimeout (timers.js:224:11)
	    at Timer.listOnTimeout (timers.js:198:5)

case 2: fierwall disabled

	root@tpahaz:/kurento-node/kurento-client-js# ./node_modules/.bin/qunit-cli -c kurentoClient:. -c wock:node_modules/wock -c test/_common.js -c test/_proxy.js test/*.js --ws_uri=ws://kms:8888/kurento

	undefinedMediaObjectCreator
	Unknown type ' { type: 'dummyUnknownType' } ', using MediaObject instead
	  ✔ Get unknown constructor

	ServerManager
	  ✔ Server manager getInfo with callback
	  ✔ Server manager getInfo with promise
	  ✔ Server manager getPipelines with promise
	  ✔ Server manager getPipelines with callback

	reconnect
	  ✖ Continue after network error
	    Died on test #2     at Object.<anonymous> (/kurento-node/kurento-client-js/test/reconnect.js:66:7)
	    at Module._compile (module.js:541:32)
	    at Object.Module._extensions..js (module.js:550:10)
	    at Module.load (module.js:458:32)
	    at tryModuleLoad (module.js:417:12)
	    at Function.Module._load (module.js:409:3)
	    at Module.require (module.js:468:17): mediaPipeline param is required
	    null != undefined
	    Expected 13 assertions, but 2 were run
	    null != undefined

	waiting
	notReconnectIfNumLessThan = 2
	Server did not respond to ping message 2.
	Pipeline: 9491c063-7ba1-431e-a8a3-a5e88a303780_kurento.MediaPipeline  pipeline_: 9491c063-7ba1-431e-a8a3-a5e88a303780_kurento.MediaPipeline
	  ✔ Waiting 2 minutes and ask again for an object

	Tests completed in 120436 milliseconds.
	8 tests of 10 passed, 2 failed.

**Please provide any additional information below.**

I have problem with reconnection. I try to run tests on two node.js versions `v6.2.2` and `v6.9.5`.
And for both experiments I have `8 tests of 10 passed, 2 failed`. 
(case 1 is shown for comparison. real problem only in case 2)

[experement-node-6.2.2.txt](https://github.com/Kurento/bugtracker/files/775182/experement-node-6.2.2.txt)
[experement-node-6.9.5.txt](https://github.com/Kurento/bugtracker/files/775186/experement-node-6.9.5.txt)

**Comment by pahaz** [comment]
The same result on node `v4.7.3`

**Comment by j1elo** [comment]
Closing due to no activity (also reconnect tests work as of today)
