### ISSUE TITLE
kms change my rtsp url

### ISSUE THREAD

**Issue by milanjya** [Kurento/bugtracker#226]
ubuntu 14.04
kurento-media-server 6.0
my rtsp url is：rtsp://192.9.200.123:554/pag://192.9.200.123:7302:f1ee0861fcb24c23b8aa7b96a4eb4114:0:MAIN:TCP
but when i use Kurento-rtsp2WebRTC，the KMS change my url to：
rtsp://192.9.200.123:554/pag:/192.9.200.123:7302:f1ee0861fcb24c23b8aa7b96a4eb4114:0:MAIN:TCP
pag:// ---------> pag:/
then my video can't play.
how can i solve it?

**Comment by virtualfunction** [comment]
Just a wild stab in the dark here but inside the `pag://192.9.200.123:7302` you have a `://` which normally what comes after the scheme / protocol part at the start of a URI,, so maybe you need to URIencode the forward slashes (i.e. i think each forward slash would become %2F)

**Comment by milanjya** [comment]
@virtualfunction  thanks first~
i try to set my rtsp url to 'rtsp://....../pag:%2F%2F......'
but the kms also change it to 'rtsp://....../pag:/......'
it means that kms decode my url and change // to /

**Comment by dhquero** [comment]
I have the same problem. One bar is removed in my RTSP URL. My Kurento version is 6.14.
Any news about this topic?

**Comment by j1elo** [comment]
What is the URL you try to open? And how it gets after one bar is removed?

**Comment by dhquero** [comment]
My original URL is:
rtsp://user:pass@127.0.0.1:8554/param1=123&uri=&&umsp://mydomain.com:1234/myid=xxxx

The Kurento removes one bar:
rtsp://user:pass@127.0.0.1:8554/param1=123&uri=&&umsp:/mydomain.com:1234/myid=xxxx

I get error "Invalid URL" in my application server. The reason is the media does not exist in my RTSP server. I need that bar which was removed by Kurento before call my RTSP server.
My RTSP server connect in other server and, then retransmit that stream in RTSP protocol.

```
2020-08-26 15:10:05.250 ERROR 17720 --- [EventExec-e2-t0] m.f.v.w.handler.HandlerOperations        : ErrorEvent in PlayerEndpoint: Invalid URI
2020-08-26 15:10:05.250  INFO 17720 --- [EventExec-e2-t0] m.f.v.w.handler.HandlerOperations        : STOP - USER: 0b68aeb4-ce0f-5051-bd47-39efc59b704b
org.kurento.client.internal.server.KurentoServerException: Object 'f925969b-acc8-4cec-9e2a-c8035ec8eb02_kurento.MediaPipeline/de4dc7c0-9b27-4673-a474-413f46e30272_kurento.PlayerEndpoint' not found (Code:40101, Type:null, Data: {"type":"MEDIA_OBJECT_NOT_FOUND"})
        at org.kurento.client.internal.transport.jsonrpc.RomClientJsonRpcClient.sendRequest(RomClientJsonRpcClient.java:264) ~[kurento-client-6.14.0.jar:6.14.0]
        at org.kurento.client.internal.transport.jsonrpc.RomClientJsonRpcClient.invoke(RomClientJsonRpcClient.java:117) ~[kurento-client-6.14.0.jar:6.14.0]
        at org.kurento.client.internal.transport.jsonrpc.RomClientJsonRpcClient.invoke(RomClientJsonRpcClient.java:99) ~[kurento-client-6.14.0.jar:6.14.0]
        at org.kurento.client.internal.client.RomManager.invoke(RomManager.java:162) ~[kurento-client-6.14.0.jar:6.14.0]
        at org.kurento.client.internal.client.RemoteObject.invoke(RemoteObject.java:186) ~[kurento-client-6.14.0.jar:6.14.0]
        at org.kurento.client.internal.client.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:182) ~[kurento-client-6.14.0.jar:6.14.0]
        at org.kurento.client.internal.client.RemoteObjectInvocationHandler.internalInvoke(RemoteObjectInvocationHandler.java:142) ~[kurento-client-6.14.0.jar:6.14.0]
        at org.kurento.client.internal.client.DefaultInvocationHandler.invoke(DefaultInvocationHandler.java:39) ~[kurento-client-6.14.0.jar:6.14.0]
        at com.sun.proxy.$Proxy66.getElementGstreamerDot(Unknown Source) ~[na:na]
        at me.fullcam.vms.websocket.handler.HandlerOperations.start(HandlerOperations.java:99) ~[main/:na]
        at me.fullcam.vms.websocket.handler.Handler.lambda$handleTextMessage$0(Handler.java:53) ~[main/:na]
        at me.fullcam.vms.websocket.handler.Handler.handleTextMessage(Handler.java:67) ~[main/:na]
        at org.springframework.web.socket.handler.AbstractWebSocketHandler.handleMessage(AbstractWebSocketHandler.java:43) ~[spring-websocket-5.2.3.RELEASE.jar:5.2.3.RELEASE]
        at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleMessage(WebSocketHandlerDecorator.java:75) ~[spring-websocket-5.2.3.RELEASE.jar:5.2.3.RELEASE]
        at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleMessage(LoggingWebSocketHandlerDecorator.java:56) ~[spring-websocket-5.2.3.RELEASE.jar:5.2.3.RELEASE]
        at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.handleMessage(ExceptionWebSocketHandlerDecorator.java:58) ~[spring-websocket-5.2.3.RELEASE.jar:5.2.3.RELEASE]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.handleTextMessage(StandardWebSocketHandlerAdapter.java:114) ~[spring-websocket-5.2.3.RELEASE.jar:5.2.3.RELEASE]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.access$000(StandardWebSocketHandlerAdapter.java:43) ~[spring-websocket-5.2.3.RELEASE.jar:5.2.3.RELEASE]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:85) ~[spring-websocket-5.2.3.RELEASE.jar:5.2.3.RELEASE]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:82) ~[spring-websocket-5.2.3.RELEASE.jar:5.2.3.RELEASE]
        at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:395) ~[tomcat-embed-websocket-9.0.30.jar:9.0.30]
        at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:119) ~[tomcat-embed-websocket-9.0.30.jar:9.0.30]
        at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:495) ~[tomcat-embed-websocket-9.0.30.jar:9.0.30]
        at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:294) ~[tomcat-embed-websocket-9.0.30.jar:9.0.30]
        at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133) ~[tomcat-embed-websocket-9.0.30.jar:9.0.30]
        at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:82) ~[tomcat-embed-websocket-9.0.30.jar:9.0.30]
        at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171) ~[tomcat-embed-websocket-9.0.30.jar:9.0.30]
        at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151) ~[tomcat-embed-websocket-9.0.30.jar:9.0.30]
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148) ~[tomcat-embed-websocket-9.0.30.jar:9.0.30]
        at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54) ~[tomcat-embed-core-9.0.30.jar:9.0.30]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59) ~[tomcat-embed-core-9.0.30.jar:9.0.30]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860) ~[tomcat-embed-core-9.0.30.jar:9.0.30]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1598) ~[tomcat-embed-core-9.0.30.jar:9.0.30]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.30.jar:9.0.30]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.30.jar:9.0.30]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

Is there any way to force Kurento to no remove the second bar?

**Comment by j1elo** [comment]
I believe this is caused by https://github.com/Kurento/kms-core/blob/56d9f2e052b6643d4c1df2837df7b5ce3ea651c9/src/server/implementation/objects/UriEndpointImpl.cpp#L47

The UriEndpoint implementation is purposely removing duplicated slashes. This behavior needs review to see why it does what it does and how to improve it to accommodate the original use case and the use case of this issue.
