### ISSUE TITLE
mDNS cannot be resolved using KMS 6.12.0 

### ISSUE THREAD

**Issue by gharia** [Kurento/bugtracker#405]
**KMS Version**:

Kurento Media Server version: 6.12.0
Found modules:
	'core' version 6.12.0
	'elements' version 6.12.0
	'filters' version 6.12.0

**Ubuntu Version**

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

**Other libraries versions**:

```
ii  gstreamer1.5-libav:amd64             1.8.1-1kurento1.16.04                      amd64        libav plugin for GStreamer
ii  gstreamer1.5-nice:amd64              0.1.15-1kurento3.16.04                     amd64        ICE library (GStreamer 1.5 plugin)
ii  gstreamer1.5-plugins-bad:amd64       1.8.1-1kurento4.16.04                      amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-base:amd64      1.8.1-1kurento1.16.04                      amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64      1.8.1-1kurento2.16.04                      amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64      1.8.1-1kurento1.16.04                      amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-pulseaudio:amd64        1.8.1-1kurento2.16.04                      amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                 1.8.1-1kurento1.16.04                      amd64        GStreamer plugins for X11 and Pango
ii  kms-core                             6.12.0-0kurento1.16.04                     amd64        Kurento Core module
ii  kms-elements                         6.12.0-0kurento1.16.04                     amd64        Kurento Elements module
ii  kms-filters                          6.12.0-0kurento1.16.04                     amd64        Kurento Filters module
ii  kms-jsonrpc                          6.12.0-0kurento1.16.04                     amd64        Kurento JSON-RPC library
ii  kmsjsoncpp                           1.6.3-1kurento1.16.04                      amd64        Kurento jsoncpp library
ii  kurento-media-server                 6.12.0-0kurento1.16.04                     amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64  1.8.1-1kurento4.16.04                      amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64 1.8.1-1kurento1.16.04                      amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64              1.8.1-1kurento2.16.04                      amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                      0.1.15-1kurento3.16.04                     amd64        ICE library (shared library)
ii  libsrtp0:amd64                       1.6.0-0kurento1.16.04                      amd64        Secure RTP (SRTP) and UST Reference Implementations - shared library
ii  libusrsctp                           0.9.2-1kurento1.16.04                      amd64        sctp-refimpl library
ii  openh264                             1.4.0-1kurento1.16.04                      amd64        OpenH264 library
ii  openh264-gst-plugins-bad-1.5:amd64   1.8.1-1kurento4.16.04                      amd64        GStreamer plugins from openh264
ii  openwebrtc-gst-plugins               0.10.0-1kurento1.16.04                     amd64        OpenWebRTC specific GStreamer plugins
```

**Client libraries**

- Language: Java
- Version:1.8

**Browsers tested**

- Chrome: Version 77.0.3865.75: FAIL 
- Firefox: Not tested
- Safari: Version 13+: FAIL
- Native library: Not tested

**System description:**

- KMS location:/usr/bin/kurento-media-server
- KMS service file location: /lib/systemd/system/kurento-media-server.service
- TURN server: `Coturn` server, version `4.5.1.1`

**What steps will reproduce the problem?**

1. Run the Kurento backed WebRTC application in `Chrome version >= 75` and `Safari version >= 13`
2. On the server-side, check the logs for ICE candidates with mDNS (with.local). For such logs, check the equivalent logs of kurento. You can grep kurento logs with the same timestamp as of received ICE candidate log.
3. In the case where you have received mDNS in ICE candidate and Kurento failed to resolve it, you may experience the WebRTC audio/video is not working. (We are using audio-only, so remote peer does not hear any sound for such cases)

**What is the expected result?**
As per the release notes of 6.12, it should resolve the mDNS and ICE candidates should be added and WebRTC should not break. 

**What happens instead?**
ICE candidates are failing to be added, maybe due to mDNS not being resolved to correct IP:Port. Added some logs in another closed issue https://github.com/Kurento/bugtracker/issues/381#issuecomment-544576693

**Does it happen with one of the tutorials?**
Have not tested any tutorials

**Please provide any additional information below**

ICE Candidate received from remote peer:
```
candidate:1990097954 1 udp 2113937151 c393b427-0f2f-4dfa-b63c-909b509c63ca.local 61318 typ host generation 0 ufrag PJr7 network-cost 999`
```

Kurento error log for this ICE candidate:
```
2019-10-21T15:58:51,225920 21450 0x00007f9ab2c81700   error kmswebrtcsession          kmswebrtcsession.c:449 kms_webrtc_session_agent_add_ice_candidate() <kmswebrtcsession729>  Adding remote candidate to ICE Agent: Agent failed, stream_id: '1'
```

**Comment by j1elo** [comment]
Given how [the code](https://github.com/Kurento/kms-elements/blob/789d25b5152ba33eb4fe917ffac5e4d6a1e80a3d/src/gst-plugins/webrtcendpoint/kmsicecandidate.c#L192) is written, you should either see one of two log messages in Kurento: either `"Error code %d: '%s'"` or `"mDNS address (%s) resolved: %s"`. This is, with the [default logging levels of Kurento](https://doc-kurento.readthedocs.io/en/latest/features/logging.html#suggested-levels), or at least with `export GST_DEBUG="3,kms*:4"`.

Also, have a look for `"Cannot parse from '%s'"`, to detect cases where the candidate string is not being parsed, at all.

If you don't see those messages in Kurento logs, it means the code is not running through that `if` condition. And of course if that's the case, the local hostname won't get resolved.

**Comment by j1elo** [comment]
Could you build a slightly different version of the code ([instructions here](https://doc-kurento.readthedocs.io/en/latest/dev/dev_guide.html#building-from-sources)) and see if it helps?

You would just have to change [this line](https://github.com/Kurento/kms-elements/blob/f19f0b2f3c8610c06c71dd44f3c710c347f7fb12/src/gst-plugins/webrtcendpoint/kmsicecandidate.c#L59) to this:

```
" (?<addr>[A-Za-z0-9.:-]+)" \
```

I'm suspicious that maybe the way the regex is built is not correct, but moving the `-` character to the end of the `[ ]` range should be definitely a valid regex syntax.

**Comment by gharia** [comment]
I don't see any log message saying `"mDNS address (%s) resolved: %s"`
But I do see ` "Error code %d: '%s'"`
```
2019-10-22T08:03:37,849426 21450 0x00007f9ab2c81700 warning kmsicecandidate           kmsicecandidate.c:203 kms_ice_candidate_update_values() <KmsIceCandidate@0x7f9a8c729c20>  Error code 0: 'Error resolving '4faf4055-3a9e-42ca-b8e4-f71401aeb134.local': Name or service not known'
2019-10-22T08:03:37,946841 21450 0x00007f9ab1c7f700 warning kmsicecandidate           kmsicecandidate.c:203 kms_ice_candidate_update_values() <KmsIceCandidate@0x7f99bc1f9110>  Error code 0: 'Error resolving '981951f3-c0ee-4a65-85b6-181e818e4f1b.local': Name or service not known'
2019-10-22T08:03:38,222478 21450 0x00007f9ab2480700 warning kmsicecandidate           kmsicecandidate.c:203 kms_ice_candidate_update_values() <KmsIceCandidate@0x7f99a4007920>  Error code 0: 'Error resolving 'e0bbc3c3-9808-4798-a229-d127cb529d03.local': Name or service not known'
```
Along with that also see following logs saying  `"Cannot parse remote candidate: %s"`. Please refer below logs, mDNS are matching with above 3 logs: 
```
2019-10-22T08:03:37,849515 21450 0x00007f9ab2c81700 warning kmsiceniceagent           kmsiceniceagent.c:451 kms_ice_nice_agent_add_ice_candidate() <KmsIceNiceAgent@0x7f9a8c1ff460>  Cannot parse remote candidate: 'candidate:914638974 1 udp 2113937151 4faf4055-3a9e-42ca-b8e4-f71401aeb134.local 55296 typ host generation 0 ufrag LV/I network-cost 999'
2019-10-22T08:03:37,946934 21450 0x00007f9ab1c7f700 warning kmsiceniceagent           kmsiceniceagent.c:451 kms_ice_nice_agent_add_ice_candidate() <KmsIceNiceAgent@0x7f9aa4718c20>  Cannot parse remote candidate: 'candidate:315564084 1 udp 2113937151 981951f3-c0ee-4a65-85b6-181e818e4f1b.local 51289 typ host generation 0 ufrag CCLv network-cost 999'
2019-10-22T08:03:38,222567 21450 0x00007f9ab2480700 warning kmsiceniceagent           kmsiceniceagent.c:451 kms_ice_nice_agent_add_ice_candidate() <KmsIceNiceAgent@0x7f9a7041f560>  Cannot parse remote candidate: 'candidate:2535687984 1 udp 2113937151 e0bbc3c3-9808-4798-a229-d127cb529d03.local 55229 typ host generation 0 ufrag 33US network-cost 999'
```

I will try the change you suggested regex change.

**Comment by j1elo** [comment]
Seems that your system is unable to resolve local addresses, and that is affecting the resolution in Kurento (but would also affect all other tools, probably you cannot ping a local address, for example)

I searched a bit and found that the error message you are getting is somewhat common.  You could try purging and reinstalling the resolver, as indicated [in this S.O. answer](https://askubuntu.com/a/860492)

Regarding the other error (the second one you mention), that's definitely a regex paraing error. Maybe the modification that I suggested helps to fix it, pease let me know when you can try it.

**Comment by gharia** [comment]
@j1elo I was able to build and run from source code (making the regex change). However, I was not able to join the room, using our application server. 

So to give you a brief idea, on our staging server, I had already installed kurento `6.12.0`. Now following your instructions, I built and run kurento from source code, after making regex changes. The KMS started successfully. However, my goal is to:

1. Run that build (built from source code) as service
2. Use the existing default modules `/etc/kurento/modules/kurento/`, that got installed with 6.12.0 release. Particularly `/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini`. Because we have added `turnUrl` in that file.

**Comment by gharia** [comment]
Okay, got it working by adding turnUrl to `/usr/local/kms-omni-build/build-RelWithDebInfo/config/kurento/WebRtcEndpoint.conf.ini` and changing ExecStart to as follow in service file
```
ExecStart=/usr/local/kms-omni-build/build-RelWithDebInfo/kurento-media-server/server/kurento-media-server --modules-path='/usr/local/kms-omni-build/build-RelWithDebInfo:/usr/lib/x86_64-linux-gnu/kurento/modules'  --modules-config-path='/usr/local/kms-omni-build/build-RelWithDebInfo/config' --conf-file='/usr/local/kms-omni-build/build-RelWithDebInfo/config/kurento.conf.json' --gst-plugin-path='/usr/local/kms-omni-build/build-RelWithDebInfo'

```

**Comment by j1elo** [comment]
Yes, the script *kms-build-run.sh* launches the build in an isolated manner, so if you want to launch it but have it integrated with the system files in `/etc/`, then you have to use all command-line arguments as seen in the script:

https://github.com/Kurento/kms-omni-build/blob/ee83e0f0ab62be8387e353c6e3d7914d5ecbc073/bin/kms-build-run.sh#L423

I think that is what you realized, because you are now including all 4 arguments in your service file.

I guess that's a possible improvement to the script that could be useful for users... letting it load the files from `/etc/` as per default setup, instead of loading them from `$PWD`.

**Comment by gharia** [comment]
Yeah, it will be useful. I did change the regex as suggested by you before building the code. But it does not solve it.

I got the logs and it's still not able to resolve the mDNS. Following are the logs:

```
2019-10-23T17:53:20,578085 8042 0x00007fc3c76f8700 warning kmsicecandidate           kmsicecandidate.c:203 kms_ice_candidate_update_values() <KmsIceCandidate@0x7fc388002660>  Error code 0: 'Error resolving '902a265c-16e8-4501-a44e-de85ea7039522.local': Name or service not known'
2019-10-23T17:53:20,578187 8042 0x00007fc3c76f8700    info webrtcendpoint            kmswebrtcendpoint.c:439 kms_webrtc_endpoint_add_ice_candidate() <kmswebrtcendpoint3>  Add ICE candidate 'candidate:2525233420 1 udp 2113937151 902a265c-16e8-4501-a44e-de85ea7039522.local 53648 typ host generation 0 ufrag Zr3n network-cost 999' for session 'kmswebrtcendpoint3-sess0'
2019-10-23T17:53:20,578242 8042 0x00007fc3c76f8700 warning kmsiceniceagent           kmsiceniceagent.c:451 kms_ice_nice_agent_add_ice_candidate() <KmsIceNiceAgent@0x7fc3b80320e0>  Cannot parse remote candidate: 'candidate:2525233420 1 udp 2113937151 902a265c-16e8-4501-a44e-de85ea7039522.local 53648 typ host generation 0 ufrag Zr3n network-cost 999'
2019-10-23T17:53:20,578274 8042 0x00007fc3c76f8700   error kmswebrtcsession          kmswebrtcsession.c:449 kms_webrtc_session_agent_add_ice_candidate() <kmswebrtcsession3>  Adding remote candidate to ICE Agent: Agent failed, stream_id: '1'
```

I was looking at the code. Following is my understanding:
1. First error(`Error code 0`) it throws the error from [kmsicecandidate.c#L203](https://github.com/Kurento/kms-elements/blob/789d25b5152ba33eb4fe917ffac5e4d6a1e80a3d/src/gst-plugins/webrtcendpoint/kmsicecandidate.c#L203). Which means it fails at [kmsicecandidate.c#L198](https://github.com/Kurento/kms-elements/blob/789d25b5152ba33eb4fe917ffac5e4d6a1e80a3d/src/gst-plugins/webrtcendpoint/kmsicecandidate.c#L198). hence it is not going to else block which is responsible for resolving mDNS.
2. This unresolved mDNS is going ahead in the code flow and it throws the second error when it reaches [kmsiceniceagent.c#L451](https://github.com/Kurento/kms-elements/blob/789d25b5152ba33eb4fe917ffac5e4d6a1e80a3d/src/gst-plugins/webrtcendpoint/kmsiceniceagent.c#L451) point. Maybe this is because it was unresolved and hence KMS cannot parse it.

So I feel that if we can fix the first error, the second one will be no longer there.

**Comment by gharia** [comment]
Hey @j1elo,  Let me know if any suggestions/changes I should try further. I appreciate your help.

Thank you.

**Comment by j1elo** [comment]
Check that your system is able to resolve mDNS candidates. To check this I guess you could `ping` some local address or maybe `nslookup`, I'm not too sure though.

Kurento just delegates the name resolution itself to the system tools, through the GLib library. So if these tools fail, GLib will also fail and Kurento just receives an error and prints it.

In your case, the error happens outside Kurento, when the function `g_resolver_lookup_by_name()` returns the error message `Name or service not known`.

**Comment by j1elo** [comment]
I've been researching the topic and have some hints:

**1. mDNS resolution must be enabled**

Check out the contents of `/etc/nsswitch.conf`, you should see something like this:

```
hosts: files mdns4_minimal [NOTFOUND=return] dns
```

If not, try fully reinstalling the package **libnss-mdns**:

```
sudo apt-get purge --yes libnss-mdns
sudo apt-get update
sudo apt-get install --yes libnss-mdns
```

Installing this package does automatically edit the config file in an appropriate way. Now the *mdns4_minimal* module should appear listed in the *hosts* line.


**2. mDNS does not work from within Docker**

See [mDNS and Crossbar.io Fabric (Docker) #21](https://github.com/crossbario/crossbar-fabric-public/issues/21)

So if you are running a Docker image, `.local` hostnames won't be correctly resolved even if you install the required packages. This happens with Kurento or whatever other software; it seems to be a Docker configuration problem / bug.

**Comment by gharia** [comment]
@j1elo Thank you for the suggestions. I am not running a Docker image. I tried reinstalling `libnss-mdns` and found that  , but still, the logs are the same. It fails to resolve mDNS:

```
2019-10-28T18:31:53,981914 1173 0x00007fd738032700 warning kmsicecandidate           kmsicecandidate.c:203 kms_ice_candidate_update_values() <KmsIceCandidate@0x7fd6fc031710>  Error code 0: 'Error resolving 'de01e13b-2790-47b1-b17d-926ad07a7ad63.local': Name or service not known'
2019-10-28T18:31:53,982024 1173 0x00007fd738032700    info webrtcendpoint            kmswebrtcendpoint.c:439 kms_webrtc_endpoint_add_ice_candidate() <kmswebrtcendpoint1>  Add ICE candidate 'candidate:3471249754 1 udp 2113937151 de01e13b-2790-47b1-b17d-926ad07a7ad63.local 52743 typ host generation 0 ufrag F7ku network-cost 999' for session 'kmswebrtcendpoint1-sess0'
2019-10-28T18:31:53,982081 1173 0x00007fd738032700 warning kmsiceniceagent           kmsiceniceagent.c:451 kms_ice_nice_agent_add_ice_candidate() <KmsIceNiceAgent@0x7fd7140c2f20>  Cannot parse remote candidate: 'candidate:3471249754 1 udp 2113937151 de01e13b-2790-47b1-b17d-926ad07a7ad63.local 52743 typ host generation 0 ufrag F7ku network-cost 999'
2019-10-28T18:31:53,982104 1173 0x00007fd738032700   error kmswebrtcsession          kmswebrtcsession.c:449 kms_webrtc_session_agent_add_ice_candidate() <kmswebrtcsession1>  Adding remote candidate to ICE Agent: Agent failed, stream_id: '1'
```
How do I check that my system is correctly resolving local addresses ? 
And as per my basic understanding, `libnss-mdns` is for local network discovery/resolution. How it will work if I get the mDNS (with.local) from the browser/client which is not in my local network? Just trying to understand, how `.local` addresses will resolve to IP:Port. Because the connecting WebRTC browser clients will always be on different networks in our case. The logs which I sent are the same case.

**Comment by j1elo** [comment]
Hi @gharia, to check if your system can resolve `.local` candidates, you can use either `ping` or `nslookup` in a console.

However, nothing of this is important now that you mentioned your use case: the `.local` candidates are only used for **LAN** networks, i.e. for WebRTC peers that can be accessed directly in the local subnet. You (and Kurento) would be able to resolve those from within the network, if *libnss-mdns* is installed.

The `.local` candidates cannot be resolved from different networks, that's exactly the purpose of mDNS :-) it *conceals* the actual IP addresses so foreign networks cannot deduce your private network topology. Even if you managed to resolve a `.local` candidate, the IP address would be irrelevant for peers that are not in the same network, as they wouldn't be able to use the IP address anyway (just as you cannot access my private address `192.168.1.24` from your network).

Local candidates are always identified by the string **typ host** in the candidate string. So if you are sure that the peers will always be in different networks, you could just ignore those candidates in your Application Server. Or let them pass, and just ignore the error messages in Kurento.

With remote peers, the actually useful candidates will always be **typ srflx**, **typ prflx**, and **typ relay** ([RTCIceCandidateType](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidateType)).

This begs the question of whether we should "hide" these error and warning messages from Kurento... as all users will see them when receiving host candidates from external networks. Maybe we should change these messages to a DEBUG level, but then we wouldn't be able to detect actual errors when resolving mDNS candidates from the local network. I'll have to think about that.

**Comment by j1elo** [comment]
> On disabling mDNS from browser settings, they were able to hear the audio

That was either a coincidence, or a very nasty bug somewhere. Make sure STUN and TURN servers are correctly configured, and have a look at the [Networking issues](https://doc-kurento.readthedocs.io/en/6.12.0/user/troubleshooting.html#networking-issues) section on the troubleshooting page.

**Comment by gharia** [comment]
Well, Coturn looks fine We have been using `use-auth-secret`. Probably I should double-check the opened UDSP port for ec2 instance. May be open all ports. 

But yeah, we can close this issue. Thanks for all your help and guidance @j1elo

**Comment by guohuoyong** [comment]
2021-07-25T15:24:09,942505 934 0x00007fe410861700 warning dtlsconnection            gstdtlsconnection.c:694 openssl_poll() <GstDtlsConnection@0x7fe40c059df0>  do_handshake encountered BIO error
2021-07-25T15:24:10,046181 934 0x00007fe40157b700 warning dtlsconnection            gstdtlsconnection.c:694 openssl_poll() <GstDtlsConnection@0x7fe40c018f10>  do_handshake encountered BIO error
2021-07-25T15:24:11,935503 934 0x00007fe400d7a700 warning dtlsconnection            gstdtlsconnection.c:694 openssl_poll() <GstDtlsConnection@0x7fe40c059df0>  do_handshake encountered BIO error
2021-07-25T15:24:12,037477 934 0x00007fe400579700 warning dtlsconnection            gstdtlsconnection.c:694 openssl_poll() <GstDtlsConnection@0x7fe40c018f10>  do_handshake encountered BIO error
2021-07-25T15:24:13,709042 934 0x00007fe42ba30700 warning kmsicecandidate           kmsicecandidate.c:107 kms_ice_candidate_update_values() <KmsIceCandidate@0x7fe42400ece0>  Cannot parse from ''

**Comment by guohuoyong** [comment]
Closing session due to exception for StandardWebSocketSession[id=6ee3f900-1d14-61d1-21d1-5bd42278b24e, uri=wss://101.133.130.87:8443/call]

org.kurento.client.internal.server.KurentoServerException: Error adding candidate (Code:40401, Type:null, Data: {"type":"ICE_ADD_CANDIDATE_ERROR"})
        at org.kurento.client.internal.transport.jsonrpc.RomClientJsonRpcClient.sendRequest(RomClientJsonRpcClient.java:264) ~[kurento-client-6.16.0.jar!/:6.16.0]
        at org.kurento.client.internal.transport.jsonrpc.RomClientJsonRpcClient.invoke(RomClientJsonRpcClient.java:117) ~[kurento-client-6.16.0.jar!/:6.16.0]
        at org.kurento.client.internal.transport.jsonrpc.RomClientJsonRpcClient.invoke(RomClientJsonRpcClient.java:99) ~[kurento-client-6.16.0.jar!/:6.16.0]
        at org.kurento.client.internal.client.RomManager.invoke(RomManager.java:162) ~[kurento-client-6.16.0.jar!/:6.16.0]
        at org.kurento.client.internal.client.RemoteObject.invoke(RemoteObject.java:186) ~[kurento-client-6.16.0.jar!/:6.16.0]
        at org.kurento.client.internal.client.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:182) ~[kurento-client-6.16.0.jar!/:6.16.0]
        at org.kurento.client.internal.client.RemoteObjectInvocationHandler.internalInvoke(RemoteObjectInvocationHandler.java:142) ~[kurento-client-6.16.0.jar!/:6.16.0]
        at org.kurento.client.internal.client.DefaultInvocationHandler.invoke(DefaultInvocationHandler.java:39) ~[kurento-client-6.16.0.jar!/:6.16.0]
        at com.sun.proxy.$Proxy60.addIceCandidate(Unknown Source) ~[na:na]
        at org.kurento.tutorial.one2onecall.UserSession.addCandidate(UserSession.java:110) ~[classes!/:6.16.0]
        at org.kurento.tutorial.one2onecall.CallHandler.handleTextMessage(CallHandler.java:95) ~[classes!/:6.16.0]
        at org.springframework.web.socket.handler.AbstractWebSocketHandler.handleMessage(AbstractWebSocketHandler.java:43) ~[spring-websocket-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
        at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleMessage(WebSocketHandlerDecorator.java:75) ~[spring-websocket-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
        at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleMessage(LoggingWebSocketHandlerDecorator.java:56) ~[spring-websocket-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
        at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.handleMessage(ExceptionWebSocketHandlerDecorator.java:58) ~[spring-websocket-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.handleTextMessage(StandardWebSocketHandlerAdapter.java:114) [spring-websocket-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.access$000(StandardWebSocketHandlerAdapter.java:43) [spring-websocket-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:85) [spring-websocket-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
        at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.
