### ISSUE TITLE
KurentoClient.getSingleton callback argument is not optional.

### ISSUE THREAD

**Issue by mvastola** [Kurento/bugtracker#434]
**Describe the bug**

Per the [JS docs](https://doc-kurento.readthedocs.io/en/6.13.0/_static/client-jsdoc/module-kurentoClient.KurentoClient.html#.getSingleton), the static `getSingleton` method on the `KurentoClient` class can optionally either return a promise or take a callback.

However, when an error occurs if the promise invocation is used (meaning no callback was passed), a second error occurs due to the lack of a callback argument. The offending code is [here](https://github.com/Kurento/kurento-client-js/blob/bb6f5d0aba3e8d7221fd466bac90a72036beff3a/lib/KurentoClient.js#L1132).

**To Reproduce**

```js
import { default as KurentoClient } from 'kurento-client';
KurentoClient.getSingleton('some invalid url`)
  .catch(err => console.warn('An error occurred.'));
```
**Expected behavior**

The warning `An error occurred.` should be printed to the console.

**Application Server**

- Language: Node.js
- Client version: 6.13.0

**Comment by mvastola** [comment]
Further, the obvious workaround is not possible as the following code:
```js
const getKurentoClientSingleton = (...args) => {
  return new Promise((resolve, reject) => {
    KurentoClient.getSingleton(...args, (error, client) => {
      if (error) {
        reject(error);
      } else {
        resolve(client);
      }
    });
  });
};
```

.. results in the following error:
```
Trace: TypeError: Cannot redefine property: then
    at Function.defineProperties (<anonymous>)
    at disguiseThenable ([...]/node_modules/kurento-client/lib/disguise.js:89:12)
    at Function.args [as getSingleton] ([...]/node_modules/kurento-client/lib/KurentoClient.js:1141:10)
```
