### ISSUE TITLE
crash on nice_agent (with  stack details in errros.log but the crash

### ISSUE THREAD

**Issue by darrenhp** [Kurento/bugtracker#504]
## Prerequisites

* [x] I have read the SUPPORT document
  

* [x] I have checked the Troubleshooting Guide
  

* [x] I have tested with the latest version of Kurento
  

## Issue description

Unexpected error 9 on netlink descriptor 555Aborted (thread 139959978587904, pid 1333)
Stack trace:
[__GI_raise]
sysdeps/unix/sysv/linux/raise.c:51 (discriminator 3)
[__GI_abort]
/build/glibc-2ORdQG/glibc-2.27/stdlib/abort.c:81
[__libc_message]
sysdeps/posix/libc_fatal.c:86
[__libc_fatal]
/lib/x86_64-linux-gnu/libc.so.6:0x8999A
[__GI___netlink_assert_response]
sysdeps/unix/sysv/linux/netlink_assert_response.c:104
[__netlink_request]
sysdeps/unix/sysv/linux/ifaddrs.c:239
[getifaddrs_internal]
sysdeps/unix/sysv/linux/ifaddrs.c:348
[__GI___getifaddrs]
sysdeps/unix/sysv/linux/ifaddrs.c:831 (discriminator 1)
[nice_interfaces_get_local_ips]
./agent/interfaces.c:355
[nice_candidate_ip_local_preference]
./agent/candidate.c:184
[nice_candidate_ice_local_preference_full]
./agent/candidate.c:150
[peer_reflexive_candidate_priority]
./agent/conncheck.c:1350
[conn_check_add_for_candidate_pair]
./agent/conncheck.c:2482
[conn_check_add_for_candidate]
./agent/conncheck.c:2528
[priv_add_remote_candidate]
./agent/agent.c:3777
[nice_agent_set_remote_candidates]
./agent/agent.c:3950

### INFO about Kurento Media Server

* Kurento version:   6.14.0
* Server OS:        18.04 (Bionic)
* Installation method:
    
  - [x] apt-get
    
  - [] Docker
    
  - [] AWS
    
  - [] Built from sources
    

### INFO about your Application Server

* Language:              Java   
* Kurento Client version:    todo   

### INFO about end-user clients

* Device(s):    
* OS(es):       
* Browser(s):   

### Commands output

```
cat /etc/lsb-release

kurento-media-server --version

dpkg -l | grep -Pi 'kurento|kms-|gst.*1.5|nice'
```
```
root@kurento-ai-nightly-online:/var/crash/
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
root@kurento-ai-nightly-online:/var/crash/
$
root@kurento-ai-nightly-online:/var/crash/
$ kurento-media-server --version

Kurento Media Server version: 6.14.0
Found modules:
	'core' version 6.14.0
	'elements' version 6.14.0
	'filters' version 6.14.0
root@kurento-ai-nightly-online:/var/crash/
$
root@kurento-ai-nightly-online:/var/crash/
$ dpkg -l | grep -Pi 'kurento|kms-|gst.*1.5|nice'
ii  gstreamer1.5-alsa:amd64                1.8.1-1kurento2.18.04                           amd64        GStreamer plugin for ALSA
ii  gstreamer1.5-libav:amd64               1.8.1-1kurento1.18.04                           amd64        libav plugin for GStreamer
ii  gstreamer1.5-libav-dbg:amd64           1.8.1-1kurento1.18.04                           amd64        libav plugin for GStreamer (debug symbols)
ii  gstreamer1.5-nice:amd64                0.1.17-0kurento1.18.04                          amd64        ICE library (GStreamer 1.5 plugin)
ii  gstreamer1.5-nice-dbgsym:amd64         0.1.17-0kurento1.18.04                          amd64        debug symbols for gstreamer1.5-nice
ii  gstreamer1.5-plugins-bad:amd64         1.8.1-1kurento4.18.04                           amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-bad-dbg:amd64     1.8.1-1kurento4.18.04                           amd64        GStreamer plugins from the "bad" set (debug symbols)
ii  gstreamer1.5-plugins-base:amd64        1.8.1-1kurento2.18.04                           amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-base-dbg:amd64    1.8.1-1kurento2.18.04                           amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64        1.8.1-1kurento4.18.04                           amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-good-dbg:amd64    1.8.1-1kurento4.18.04                           amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64        1.8.1-1kurento1.18.04                           amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-plugins-ugly-dbg:amd64    1.8.1-1kurento1.18.04                           amd64        GStreamer plugins from the "ugly" set (debug symbols)
ii  gstreamer1.5-pulseaudio:amd64          1.8.1-1kurento4.18.04                           amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                   1.8.1-1kurento2.18.04                           amd64        GStreamer plugins for X11 and Pango
ii  kms-core                               6.14.0-0kurento1.18.04                          amd64        Kurento Core module
ii  kms-core-dbg                           6.14.0-0kurento1.18.04                          amd64        Kurento Core module
ii  kms-elements                           6.14.0-0kurento1.18.04                          amd64        Kurento Elements module
ii  kms-elements-dbg                       6.14.0-0kurento1.18.04                          amd64        Kurento Elements module
ii  kms-filters                            6.14.0-0kurento1.18.04                          amd64        Kurento Filters module
ii  kms-filters-dbg                        6.14.0-0kurento1.18.04                          amd64        Kurento Filters module
ii  kms-jsonrpc                            6.14.0-0kurento1.18.04                          amd64        Kurento JSON-RPC library
ii  kms-jsonrpc-dbg                        6.14.0-0kurento1.18.04                          amd64        Kurento JSON-RPC library
ii  kmsjsoncpp                             1.6.3-1kurento1.18.04                           amd64        Kurento jsoncpp library
ii  kmsjsoncpp-dbg                         1.6.3-1kurento1.18.04                           amd64        Kurento jsoncpp library
ii  kurento-dbg                            6.14.0-0kurento1.18.04                          amd64        Meta-package that installs debug symbols
ii  kurento-media-server                   6.14.0-0kurento1.18.04                          amd64        Kurento Media Server
ii  kurento-media-server-dbg               6.14.0-0kurento1.18.04                          amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64    1.8.1-1kurento4.18.04                           amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64   1.8.1-1kurento2.18.04                           amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64                1.8.1-1kurento2.18.04                           amd64        Core GStreamer libraries and elements
ii  libgstreamer1.5-0-dbg:amd64            1.8.1-1kurento2.18.04                           amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                        0.1.17-0kurento1.18.04                          amd64        ICE library (shared library)
ii  libnice10-dbgsym:amd64                 0.1.17-0kurento1.18.04                          amd64        debug symbols for libnice10
ii  libsrtp0:amd64                         1.6.0-0kurento1.18.04                           amd64        Secure RTP (SRTP) and UST Reference Implementations - shared library
ii  libusrsctp                             0.9.2-1kurento1.18.04                           amd64        sctp-refimpl library
ii  openh264                               1.4.0-1kurento1.18.04                           amd64        OpenH264 library
ii  openh264-gst-plugins-bad-1.5:amd64     1.8.1-1kurento4.18.04                           amd64        GStreamer plugins from openh264
ii  openwebrtc-gst-plugins                 0.10.0-1kurento1.18.04                          amd64        OpenWebRTC specific GStreamer plugins
ii  openwebrtc-gst-plugins-dbg             0.10.0-1kurento1.18.04                          amd64        OpenWebRTC specific GStreamer plugins
```

**Comment by darrenhp** [comment]
the crash file

**Comment by darrenhp** [comment]
The crash file is too large(200MB) to upload it to github;
And the "full" stack is below
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f4b089ec8b1 in __GI_abort () at abort.c:79
#2  0x00005564364c89ed in Debug::safe_abort () at ./server/death_handler.cpp:299
#3  Debug::DeathHandler::SignalHandler (sig=<optimized out>, secret=<optimized out>) at ./server/death_handler.cpp:600
#4  <signal handler called>
#5  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#6  0x00007f4b089ec8b1 in __GI_abort () at abort.c:79
#7  0x00007f4b08a35655 in __libc_message (action=(do_abort | do_backtrace), fmt=0x7f4b08b629f6 "%s", fmt=0x7f4b08b629f6 "%s", action=(do_abort | do_backtrace))
    at ../sysdeps/posix/libc_fatal.c:181
#8  0x00007f4b08a3599a in __GI___libc_fatal (message=<optimized out>) at ../sysdeps/posix/libc_fatal.c:191
#9  0x00007f4b08aee797 in __GI___netlink_assert_response (fd=555, result=result@entry=-1) at ../sysdeps/unix/sysv/linux/netlink_assert_response.c:102
#10 0x00007f4b08aeb36a in __netlink_request (h=h@entry=0x7f4af8ce3c10, type=type@entry=22) at ../sysdeps/unix/sysv/linux/ifaddrs.c:174
#11 0x00007f4b08aeb529 in getifaddrs_internal (ifap=ifap@entry=0x7f4af8ce3cb8) at ../sysdeps/unix/sysv/linux/ifaddrs.c:348
#12 0x00007f4b08aec380 in __GI___getifaddrs (ifap=ifap@entry=0x7f4af8ce3cb8) at ../sysdeps/unix/sysv/linux/ifaddrs.c:830
#13 0x00007f4b0417b632 in nice_interfaces_get_local_ips (include_loopback=include_loopback@entry=1) at interfaces.c:355
#14 0x00007f4b04165d53 in nice_candidate_ip_local_preference (candidate=candidate@entry=0x7f4ac418c0b0) at candidate.c:182
#15 0x00007f4b041660fd in nice_candidate_ice_local_preference (candidate=0x7f4ac418c0b0) at candidate.c:242
#16 nice_candidate_ice_priority (candidate=candidate@entry=0x7f4ac418c0b0, reliable=<optimized out>, nat_assisted=nat_assisted@entry=0) at candidate.c:352
#17 0x00007f4b04174755 in peer_reflexive_candidate_priority (local_candidate=0x7f4ac43b8c70, agent=0x7f4ab02bb010) at conncheck.c:1347
#18 stun_request_priority (local_candidate=0x7f4ac43b8c70, agent=0x7f4ab02bb010) at conncheck.c:1370
#19 priv_add_new_check_pair (initial_state=NICE_CHECK_FROZEN, remote=<optimized out>, local=0x7f4ac43b8c70, component=<optimized out>, stream_id=1, agent=0x7f4ab02bb010)
    at conncheck.c:2384
#20 priv_conn_check_add_for_candidate_pair_matched (agent=0x7f4ab02bb010, stream_id=1, component=0x7f4af0bf7b90, local=0x7f4ac43b8c70, remote=<optimized out>,
    initial_state=NICE_CHECK_FROZEN) at conncheck.c:2433
#21 0x00007f4b04175f74 in conn_check_add_for_candidate_pair (agent=0x7f4ab02bb010, stream_id=1, component=0x7f4af0bf7b90, local=0x7f4ac43b8c70, remote=0x7f4ac418c330)
    at conncheck.c:2482
#22 0x00007f4b04175fd8 in conn_check_add_for_candidate (agent=agent@entry=0x7f4ab02bb010, stream_id=stream_id@entry=1, component=0x7f4af0bf7b90,
    remote=remote@entry=0x7f4ac418c330) at conncheck.c:2525
#23 0x00007f4b0416cfc6 in priv_add_remote_candidate (foundation=0x7f4a7030f55c "0", password=<optimized out>, username=<optimized out>, priority=<optimized out>,
    transport=NICE_CANDIDATE_TRANSPORT_UDP, base_addr=0x7f4a7030f534, addr=0x7f4a7030f518, type=<optimized out>, component_id=<optimized out>, stream_id=<optimized out>,
    agent=0x7f4ab02bb010) at agent.c:3777
#24 _set_remote_candidates_locked (agent=agent@entry=0x7f4ab02bb010, stream=0x7f4af05d75a0, component=0x7f4af0bf7b90, candidates=candidates@entry=0x556437d422b0)
    at agent.c:3901
#25 0x00007f4b0416d461 in nice_agent_set_remote_candidates (agent=0x7f4ab02bb010, stream_id=1, component_id=2, candidates=candidates@entry=0x556437d422b0) at agent.c:3950
#26 0x00007f4b043b60e9 in kms_ice_nice_agent_add_ice_candidate (self=0x7f4aac41cea0, candidate=0x7f4ac40b8290, stream_id=<optimized out>)
    at ./src/gst-plugins/webrtcendpoint/kmsiceniceagent.c:504
#27 0x00007f4b043b062b in kms_webrtc_session_agent_add_ice_candidate (self=self@entry=0x7f4a88117100, candidate=candidate@entry=0x7f4ac40b8290,
    allow_error=allow_error@entry=1) at ./src/gst-plugins/webrtcendpoint/kmswebrtcsession.c:449
#28 0x00007f4b043b07b2 in kms_webrtc_session_add_ice_candidate (self=self@entry=0x7f4a88117100, candidate=0x7f4ac40b8290)
    at ./src/gst-plugins/webrtcendpoint/kmswebrtcsession.c:878
#29 0x00007f4b043b6bf3 in __kms_webrtc_marshal_BOOLEAN__OBJECT (closure=0x7f4ac8017320, return_value=0x7f4af8ce44f0, n_param_values=<optimized out>,
    param_values=0x7f4af8ce43d0, invocation_hint=<optimized out>, marshal_data=<optimized out>) at ./src/gst-plugins/webrtcendpoint/kms-webrtc-marshal.c:119
#30 0x00007f4b0a30810d in g_closure_invoke (closure=0x7f4ac8017320, return_value=0x7f4af8ce44f0, n_param_values=2, param_values=0x7f4af8ce43d0,
    invocation_hint=0x7f4af8ce4350) at ../../../../gobject/gclosure.c:804
#31 0x00007f4b0a31ade8 in signal_emit_unlocked_R (node=node@entry=0x7f4ac8080370, detail=detail@entry=0, instance=instance@entry=0x7f4a88117100,
    emission_return=emission_return@entry=0x7f4af8ce44f0, instance_and_params=instance_and_params@entry=0x7f4af8ce43d0) at ../../../../gobject/gsignal.c:3673
#32 0x00007f4b0a3230af in g_signal_emit_valist (instance=instance@entry=0x7f4a88117100, signal_id=signal_id@entry=81, detail=<optimized out>,
    var_args=var_args@entry=0x7f4af8ce45e8) at ../../../../gobject/gsignal.c:3401
#33 0x00007f4b0a324608 in g_signal_emit_by_name (instance=0x7f4a88117100, detailed_signal=detailed_signal@entry=0x7f4b043b7e29 "add-ice-candidate")
    at ../../../../gobject/gsignal.c:3487
#34 0x00007f4b043b210f in kms_webrtc_endpoint_add_ice_candidate (self=self@entry=0x7f4adcb9b050, sess_id=<optimized out>, candidate=0x7f4ac40b8290)
    at ./src/gst-plugins/webrtcendpoint/kmswebrtcendpoint.c:475
#35 0x00007f4b043b6de8 in __kms_webrtc_marshal_BOOLEAN__STRING_OBJECT (closure=0x7f4ac80d3b10, return_value=0x7f4af8ce4a90, n_param_values=<optimized out>,
    param_values=0x7f4af8ce4950, invocation_hint=<optimized out>, marshal_data=<optimized out>) at ./src/gst-plugins/webrtcendpoint/kms-webrtc-marshal.c:235
#36 0x00007f4b0a30810d in g_closure_invoke (closure=0x7f4ac80d3b10, return_value=0x7f4af8ce4a90, n_param_values=3, param_values=0x7f4af8ce4950,
    invocation_hint=0x7f4af8ce48d0) at ../../../../gobject/gclosure.c:804
#37 0x00007f4b0a31ade8 in signal_emit_unlocked_R (node=node@entry=0x7f4ac80cd7f0, detail=detail@entry=0, instance=instance@entry=0x7f4adcb9b050,
    emission_return=emission_return@entry=0x7f4af8ce4a90, instance_and_params=instance_and_params@entry=0x7f4af8ce4950) at ../../../../gobject/gsignal.c:3673
#38 0x00007f4b0a3230af in g_signal_emit_valist (instance=instance@entry=0x7f4adcb9b050, signal_id=signal_id@entry=42, detail=<optimized out>,
    var_args=var_args@entry=0x7f4af8ce4b88) at ../../../../gobject/gsignal.c:3401
#39 0x00007f4b0a324608 in g_signal_emit_by_name (instance=0x7f4adcb9b050, detailed_signal=detailed_signal@entry=0x7f4b046bb1a0 "add-ice-candidate")
    at ../../../../gobject/gsignal.c:3487
#40 0x00007f4b0466564b in kurento::WebRtcEndpointImpl::addIceCandidate (this=0x7f4ad4652100, candidate=...)
    at ./src/server/implementation/objects/WebRtcEndpointImpl.cpp:799
#41 0x00007f4b046a7b69 in kurento::WebRtcEndpointMethodAddIceCandidate::invoke (this=this@entry=0x7f4af8ce4e10, obj=warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<kurento::MediaObjectImpl*, kurento::MediaSet::ref(kurento::MediaObjectImpl*)::{lambda(kurento::MediaObjectImpl*)#1}, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<kurento::MediaObjectImpl*, kurento::MediaSet::ref(kurento::MediaObjectImpl*)::{lambda(kurento::MediaObjectImpl*)#1}, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'

std::shared_ptr<kurento::WebRtcEndpoint> (use count 5, weak count 16) = {...}) at ./src/server/interface/generated-cpp/WebRtcEndpointInternal.cpp:43
#42 0x00007f4b04690b2c in kurento::WebRtcEndpointImpl::invoke (this=<optimized out>, obj=warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<kurento::MediaObjectImpl*, kurento::MediaSet::ref(kurento::MediaObjectImpl*)::{lambda(kurento::MediaObjectImpl*)#1}, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<kurento::MediaObjectImpl*, kurento::MediaSet::ref(kurento::MediaObjectImpl*)::{lambda(kurento::MediaObjectImpl*)#1}, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
std::shared_ptr<kurento::MediaObjectImpl> (use count 5, weak count 16) = {...},
    methodName=..., params=..., response=...) at ./src/server/implementation/generated-cpp/WebRtcEndpointImplInternal.cpp:52
#43 0x0000556436496aa0 in kurento::ServerMethods::invoke (this=<optimized out>, params=..., response=...) at ./server/ServerMethods.cpp:603
#44 0x00007f4b099f8177 in std::function<void (Json::Value const&, Json::Value&)>::operator()(Json::Value const&, Json::Value&) const (__args#1=..., __args#0=...,
    this=<optimized out>) at /usr/include/c++/7/bits/std_function.h:706
#45 kurento::JsonRpc::Handler::process (this=this@entry=0x556437b4f010, msg=..., _response=...) at ./src/JsonRpcHandler.cpp:122
#46 0x000055643649af8a in kurento::ServerMethods::process (this=0x556437b4f000, requestStr=..., responseStr="", sessionId="186b0a32-b071-4b5e-b36d-50bc8445766d")
    at ./server/ServerMethods.cpp:277
#47 0x00005564365035c7 in kurento::WebSocketTransport::processMessage<websocketpp::server<websocketpp::config::asio> > (this=0x556437e94a00, s=0x556437e94b18,
    hdl=std::weak_ptr<void> (use count 3, weak count 7) = {...}, msg=...) at ./server/transport/websocket/WebSocketTransport.cpp:520
#48 0x00005564364e942f in std::__invoke_impl<void, void (kurento::WebSocketTransport::*&)(websocketpp::server<websocketpp::config::asio>*, std::weak_ptr<void>, std::shared_ptr<websocketpp::message_buffer::message<websocketpp::message_buffer::alloc::con_msg_manager> >), kurento::WebSocketTransport*&, websocketpp::server<websocketpp::config::asio>*&, std::weak_ptr<void>, std::shared_ptr<websocketpp::message_buffer::message<websocketpp::message_buffer::alloc::con_msg_manager> > > (__t=<optimized out>,
    __f=<optimized out>) at /usr/include/c++/7/bits/invoke.h:73
#49 std::__invoke<void (kurento::WebSocketTransport::*&)(websocketpp::server<websocketpp::config::asio>*, std::weak_ptr<void>, std::shared_ptr<websocketpp::message_buffer::message<websocketpp::message_buffer::alloc::con_msg_manager> >), kurento::WebSocketTransport*&, websocketpp::server<websocketpp::config::asio>*&, std::weak_ptr<void>, std::shared_ptr<websocketpp::message_buffer::message<websocketpp::message_buffer::alloc::con_msg_manager> > > (__fn=<optimized out>) at /usr/include/c++/7/bits/invoke.h:95
#50 std::_Bind<void (kurento::WebSocketTransport::*(kurento::WebSocketTransport*, websocketpp::server<websocketpp::config::asio>*, std::_Placeholder<1>, std::_Placeholder<2>))(websocketpp::server<websocketpp::config::asio>*, std::weak_ptr<void>, std::shared_ptr<websocketpp::message_buffer::message<websocketpp::message_buffer::alloc::con_msg_manager> >)>::__call<void, std::weak_ptr<void>&&, std::shared_ptr<websocketpp::message_buffer::message<websocketpp::message_buffer::alloc::con_msg_manager> >&&, 0ul, 1ul, 2ul, 3ul>(std::tuple<std::weak_ptr<void>&&, std::shared_ptr<websocketpp::message_buffer::message<websocketpp::message_buffer::alloc::con_msg_manager> >&&>&&, std::_Index_tuple<0ul, 1ul, 2ul, 3ul>) (__args=..., this=<optimized out>) at /usr/include/c++/7/functional:467
#51 std::_Bind<void (kurento::WebSocketTransport::*(kurento::WebSocketTransport*, websocketpp::server<websocketpp::config::asio>*, std::_Placeholder<1>, std::_Placeholder<2>))(websocketpp::server<websocketpp::config::asio>*, std::weak_ptr<void>, std::shared_ptr<websocketpp::message_buffer::message<websocketpp::message_buffer::alloc::con_msg_manager> >)>::operator()<std::weak_ptr<void>, std::shared_ptr<websocketpp::message_buffer::message<websocketpp::message_buffer::alloc::con_msg_manager> >, void>(std::weak_ptr<void>&&, std::shared_ptr<websocketpp::message_buffer::message<websocketpp::message_buffer::alloc::con_msg_manager> >&&) (this=<optimized out>)
    at /usr/include/c++/7/functional:551
#52 std::_Function_handler<void (std::weak_ptr<void>, std::shared_ptr<websocketpp::message_buffer::message<websocketpp::message_buffer::alloc::con_msg_manager> >), std::_Bind<void (kurento::WebSocketTransport::*(kurento::WebSocketTransport*, websocketpp::server<websocketpp::config::asio>*, std::_Placeholder<1>, std::_Placeholder<2>))(websocketpp::server<websocketpp::config::asio>*, std::weak_ptr<void>, std::shared_ptr<websocketpp::message_buffer::message<websocketpp::message_buffer::alloc::con_msg_manager> >)> >::_M_invoke(std::_Any_data const&, std::weak_ptr<void>&&, std::shared_ptr<websocketpp::message_buffer::message<websocketpp::message_buffer::alloc::con_msg_manager> >&&) (
    __functor=..., __args#0=..., __args#1=...) at /usr/include/c++/7/bits/std_function.h:316
#53 0x000055643651f042 in std::function<void (std::weak_ptr<void>, std::shared_ptr<websocketpp::message_buffer::message<websocketpp::message_buffer::alloc::con_msg_manager> >)>::operator()(std::weak_ptr<void>, std::shared_ptr<websocketpp::message_buffer::message<websocketpp::message_buffer::alloc::con_msg_manager> >) const (
    __args#1=std::shared_ptr<websocketpp::message_buffer::message<websocketpp::message_buffer::alloc::con_msg_manager>> (use count -728296336, weak count 32585) = {...},
    __args#0=std::weak_ptr<void> (use count -1075302028, weak count -335545185) = {...}, this=0x7f4ae0a5daf0) at /usr/include/c++/7/bits/std_function.h:706
#54 websocketpp::connection<websocketpp::config::asio>::handle_read_frame (this=0x7f4ae0a5d010, ec=..., bytes_transferred=458)
    at /usr/include/websocketpp/impl/connection_impl.hpp:1100
#55 0x00005564364fb428 in std::function<void (std::error_code const&, unsigned long)>::operator()(std::error_code const&, unsigned long) const (__args#1=<optimized out>,
    __args#0=..., this=0x7f4af8ce5a60) at /usr/include/c++/7/bits/std_function.h:706
#56 websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::handle_async_read(std::function<void (std::error_code const&, unsigned long)>, boost::system::error_code const&, unsigned long) (this=0x7f4ae0a5d010, handler=..., ec=..., bytes_transferred=458)
    at /usr/include/websocketpp/transport/asio/connection.hpp:896
#57 0x0000556436510308 in std::__invoke_impl<void, void (websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*&)(std::function<void (std::error_code const&, unsigned long)>, boost::system::error_code const&, unsigned long), std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config> >&, std::function<void (std::error_code const&, unsigned long)>&, boost::system::error_code&, unsigned long&>(std::__invoke_memfun_deref, void (websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*&)(std::function<void (std::error_code const&, unsigned long)>, boost::system::error_code const&, unsigned long), std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config> >&, std::function<void (std::error_code const&, unsigned long)>&, boost::system::error_code&, unsigned long&) (__t=<error reading variable: Cannot access memory at address 0xfff83488e8000008>,
    __f=@0x5564364fb3a8: &virtual table offset -1146855186136217518, this adjustment 53748016519054998) at /usr/include/c++/7/bits/invoke.h:73
#58 std::__invoke<void (websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*&)(std::function<void (std::error_code const&, unsigned long)>, boost::system::error_code const&, unsigned long), std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config> >&, std::function<void (std::error_code const&, unsigned long)>&, boost::system::error_code&, unsigned long&>(void (websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*&)(std::function<void (std::error_code const&, unsigned long)>, boost::system::error_code const&, unsigned long), std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config> >&, std::function<void (std::error_code const&, unsigned long)>&, boost::system::error_code&, unsigned long&) (
    __fn=@0x5564364fb3a8: &virtual table offset -1146855186136217518, this adjustment 53748016519054998) at /usr/include/c++/7/bits/invoke.h:95
#59 std::_Bind<void (websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*(std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config> >, std::function<void (std::error_code const&, unsigned long)>, std::_Placeholder<1>, std::_Placeholder<2>))(std::function<void (std::error_code const&, unsigned long)>, boost::system::error_code const&, unsigned long)>::__call<void, boost::system::error_code&, unsigned long&, 0ul, 1ul, 2ul, 3ul>(std::tuple<boost::system::error_code&, unsigned long&>&&, std::_Index_tuple<0ul, 1ul, 2ul, 3ul>) (__args=...,
    this=0x5564364fb3a8 <websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::handle_async_read(std::function<void (std::error_code const&, unsigned long)>, boost::system::error_code const&, unsigned long)+8>) at /usr/include/c++/7/functional:467
#60 std::_Bind<void (websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*(std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config> >, std::function<void (std::error_code const&, unsigned long)>, std::_Placeholder<1>, std::_Placeholder<2>))(std::function<void (std::error_code const&, unsigned long)>, boost::system::error_code const&, unsigned long)>::operator()<boost::system::error_code&, unsigned long&, void>(boost::system::error_code&, unsigned long&) (
    this=0x5564364fb3a8 <websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::handle_async_read(std::function<void (std::error_code const&, unsigned long)>, boost::system::error_code const&, unsigned long)+8>) at /usr/include/c++/7/functional:551
#61 websocketpp::transport::asio::custom_alloc_handler<std::_Bind<void (websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*(std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config> >, std::function<void (std::error_code const&, unsigned long)>, std::_Placeholder<1>, std::_Placeholder<2>))(std::function<void (std::error_code const&, unsigned long)>, boost::system::error_code const&, unsigned long)> >::operator()<boost::system::error_code, unsigned long>(boost::system::error_code, unsigned long) (arg2=458, arg1=...,
    this=0x5564364fb3a0 <websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::handle_async_read(std::function<void (std::error_code const&, unsigned long)>, boost::system::error_code const&, unsigned long)>) at /usr/include/websocketpp/transport/asio/base.hpp:106
#62 boost::asio::detail::binder2<websocketpp::transport::asio::custom_alloc_handler<std::_Bind<void (websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*(std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config> >, std::function<void (std::error_code const&, unsigned long)>, std::_Placeholder<1>, std::_Placeholder<2>))(std::function<void (std::error_code const&, unsigned long)>, boost::system::error_code const&, unsigned long)> >, boost::system::error_code, unsigned long>::operator()() (
    this=0x5564364fb3a0 <websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::handle_async_read(std::function<void (std::error_code const&, unsigned long)>, boost::system::error_code const&, unsigned long)>) at /usr/include/boost/asio/detail/bind_handler.hpp:127
#63 boost::asio::asio_handler_invoke<boost::asio::detail::binder2<websocketpp::transport::asio::custom_alloc_handler<std::_Bind<void (websocketpp::transport::asio::connectio

...
...
...

```
