### ISSUE TITLE
crash with a coredump 

### ISSUE THREAD

**Issue by darrenhp** [Kurento/bugtracker#510]
## Prerequisites

* [x] I have read the SUPPORT document
  

* [x] I have checked the Troubleshooting Guide
  

* [x] I have tested with the latest version of Kurento
  

## Context
crash;
crash file can download from https://www.dropbox.com/s/1pyw9b8x8j8ber5/_usr_bin_kurento-media-server.1000.crash.202007281224.zip?dl=0

(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f5c117e18b1 in __GI_abort () at abort.c:79
#2  0x00005585e9e7d9ed in Debug::safe_abort () at ./server/death_handler.cpp:299
#3  Debug::DeathHandler::SignalHandler (sig=<optimized out>, secret=<optimized out>) at ./server/death_handler.cpp:600
#4  <signal handler called>
#5  0x00007f5c12e3ee1f in magazine_cache_trim (allocator=0x7f5c130ebd20 <allocator>, stamp=<optimized out>,
    ix=<optimized out>) at ../../../../glib/gslice.c:679
#6  magazine_cache_push_magazine (ix=<optimized out>, magazine_chunks=<optimized out>, count=51)
    at ../../../../glib/gslice.c:710
#7  0x00007f5c12e40013 in thread_memory_magazine2_unload (tmem=<optimized out>, ix=<optimized out>)
    at ../../../../glib/gslice.c:809
#8  g_slice_free1 (mem_size=<optimized out>, mem_block=0x7f5bf4738ca0) at ../../../../glib/gslice.c:1118
#9  0x00007f5c133d4019 in gst_structure_free (structure=<optimized out>) at gststructure.c:392
#10 0x00007f5c1339d29f in _gst_event_free (event=0x7f5bf0407350) at gstevent.c:225
#11 0x00007f5c133ab100 in gst_mini_object_replace (olddata=olddata@entry=0x7f5bcc0229c8,
    newdata=newdata@entry=0x7f5bcc306b20) at gstminiobject.c:513
#12 0x00007f5c133accd3 in gst_event_replace (new_event=0x7f5bcc306b20, old_event=0x7f5bcc0229c8) at ../gst/gstevent.h:297
#13 store_sticky_event (pad=pad@entry=0x7f5bf46f47c0, event=event@entry=0x7f5bcc306b20) at gstpad.c:5042
#14 0x00007f5c133adead in gst_pad_send_event_unchecked (pad=pad@entry=0x7f5bf46f47c0, event=event@entry=0x7f5bcc306b20,
    type=<optimized out>, type@entry=GST_PAD_PROBE_TYPE_EVENT_DOWNSTREAM) at gstpad.c:5604
#15 0x00007f5c133ae75d in gst_pad_push_event_unchecked (pad=pad@entry=0x7f5be0160ba0, event=0x7f5bcc306b20,
    type=type@entry=GST_PAD_PROBE_TYPE_EVENT_DOWNSTREAM) at gstpad.c:5240
#16 0x00007f5c133aeac9 in push_sticky (pad=pad@entry=0x7f5be0160ba0, ev=ev@entry=0x7f5bb30aa1d0,
    user_data=user_data@entry=0x7f5bb30aa240) at gstpad.c:3785
#17 0x00007f5c133ac86f in events_foreach (pad=pad@entry=0x7f5be0160ba0, func=func@entry=0x7f5c133aea10 <push_sticky>,
    user_data=user_data@entry=0x7f5bb30aa240) at gstpad.c:601
#18 0x00007f5c133b85cf in check_sticky (event=0x7f5bcc306b20, pad=0x7f5be0160ba0) at gstpad.c:3842
#19 gst_pad_push_event (pad=0x7f5be0160ba0, event=event@entry=0x7f5bcc306b20) at gstpad.c:5371
#20 0x00007f5bd1c254b4 in gst_queue_push (queue=0x7f5be078c630) at gstqueue.c:1553
#21 gst_queue_loop (pad=<optimized out>) at gstqueue.c:1638
#22 0x00007f5c133e1a10 in gst_task_func (task=0x7f5bd823d050) at gsttask.c:344
#23 0x00007f5c12e4ab40 in g_thread_pool_thread_proxy (data=<optimized out>) at ../../../../glib/gthreadpool.c:307
#24 0x00007f5c12e4a175 in g_thread_proxy (data=0x7f5bdc5ff050) at ../../../../glib/gthread.c:784
---Type <return> to continue, or q <return> to quit---
#25 0x00007f5c13f1e6db in start_thread (arg=0x7f5bb30ab700) at pthread_create.c:463
#26 0x00007f5c118c2a3f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

### INFO about Kurento Media Server

* Kurento version:  6.14.0 
* Server OS:      18.04 (Bionic)   
* Installation method:
    
  - [x] apt-get
    
  - [] Docker
    
  - [] AWS
    
  - [] Built from sources
    

### INFO about your Application Server

* Language:             Java    
* Kurento Client version:    6.13.1 

### INFO about end-user clients

* Device(s):    
* OS(es):       
* Browser(s):   

### Commands output

```
cat /etc/lsb-release

kurento-media-server --version

dpkg -l | grep -Pi 'kurento|kms-|gst.*1.5|nice'
```
```
root@kurento-online-hz-20200604002:/var/crash/1/
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
root@kurento-online-hz-20200604002:/var/crash/1/
$
root@kurento-online-hz-20200604002:/var/crash/1/
$ kurento-media-server --version
Kurento Media Server version: 6.14.0
Found modules:
	'core' version 6.14.0
	'elements' version 6.14.0
	'filters' version 6.14.0
root@kurento-online-hz-20200604002:/var/crash/1/
$
root@kurento-online-hz-20200604002:/var/crash/1/
$ dpkg -l | grep -Pi 'kurento|kms-|gst.*1.5|nice'
ii  gstreamer1.5-alsa:amd64                1.8.1-1kurento2.18.04                           amd64        GStreamer plugin for ALSA
ii  gstreamer1.5-libav:amd64               1.8.1-1kurento1.18.04                           amd64        libav plugin for GStreamer
ii  gstreamer1.5-libav-dbg:amd64           1.8.1-1kurento1.18.04                           amd64        libav plugin for GStreamer (debug symbols)
ii  gstreamer1.5-nice:amd64                0.1.17-0kurento1.18.04                          amd64        ICE library (GStreamer 1.5 plugin)
ii  gstreamer1.5-nice-dbgsym:amd64         0.1.17-0kurento1.18.04                          amd64        debug symbols for gstreamer1.5-nice
ii  gstreamer1.5-plugins-bad:amd64         1.8.1-1kurento4.18.04                           amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.5-plugins-bad-dbg:amd64     1.8.1-1kurento4.18.04                           amd64        GStreamer plugins from the "bad" set (debug symbols)
ii  gstreamer1.5-plugins-base:amd64        1.8.1-1kurento2.18.04                           amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-base-dbg:amd64    1.8.1-1kurento2.18.04                           amd64        GStreamer plugins from the "base" set
ii  gstreamer1.5-plugins-good:amd64        1.8.1-1kurento4.18.04                           amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-good-dbg:amd64    1.8.1-1kurento4.18.04                           amd64        GStreamer plugins from the "good" set
ii  gstreamer1.5-plugins-ugly:amd64        1.8.1-1kurento1.18.04                           amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.5-plugins-ugly-dbg:amd64    1.8.1-1kurento1.18.04                           amd64        GStreamer plugins from the "ugly" set (debug symbols)
ii  gstreamer1.5-pulseaudio:amd64          1.8.1-1kurento4.18.04                           amd64        GStreamer plugin for PulseAudio
ii  gstreamer1.5-x:amd64                   1.8.1-1kurento2.18.04                           amd64        GStreamer plugins for X11 and Pango
ii  kms-core                               6.14.0-0kurento1.18.04                          amd64        Kurento Core module
ii  kms-core-dbg                           6.14.0-0kurento1.18.04                          amd64        Kurento Core module
ii  kms-elements                           6.14.0-0kurento1.18.04                          amd64        Kurento Elements module
ii  kms-elements-dbg                       6.14.0-0kurento1.18.04                          amd64        Kurento Elements module
ii  kms-filters                            6.14.0-0kurento1.18.04                          amd64        Kurento Filters module
ii  kms-filters-dbg                        6.14.0-0kurento1.18.04                          amd64        Kurento Filters module
ii  kms-jsonrpc                            6.14.0-0kurento1.18.04                          amd64        Kurento JSON-RPC library
ii  kms-jsonrpc-dbg                        6.14.0-0kurento1.18.04                          amd64        Kurento JSON-RPC library
ii  kmsjsoncpp                             1.6.3-1kurento1.18.04                           amd64        Kurento jsoncpp library
ii  kmsjsoncpp-dbg                         1.6.3-1kurento1.18.04                           amd64        Kurento jsoncpp library
ii  kurento-dbg                            6.14.0-0kurento1.18.04                          amd64        Meta-package that installs debug symbols
ii  kurento-media-server                   6.14.0-0kurento1.18.04                          amd64        Kurento Media Server
ii  kurento-media-server-dbg               6.14.0-0kurento1.18.04                          amd64        Kurento Media Server
ii  libgstreamer-plugins-bad1.5-0:amd64    1.8.1-1kurento4.18.04                           amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.5-0:amd64   1.8.1-1kurento2.18.04                           amd64        GStreamer libraries from the "base" set
ii  libgstreamer1.5-0:amd64                1.8.1-1kurento2.18.04                           amd64        Core GStreamer libraries and elements
ii  libgstreamer1.5-0-dbg:amd64            1.8.1-1kurento2.18.04                           amd64        Core GStreamer libraries and elements
ii  libnice10:amd64                        0.1.17-0kurento1.18.04                          amd64        ICE library (shared library)
ii  libnice10-dbgsym:amd64                 0.1.17-0kurento1.18.04                          amd64        debug symbols for libnice10
ii  libsrtp0:amd64                         1.6.0-0kurento1.18.04                           amd64        Secure RTP (SRTP) and UST Reference Implementations - shared library
ii  libusrsctp                             0.9.2-1kurento1.18.04                           amd64        sctp-refimpl library
ii  openh264                               1.4.0-1kurento1.18.04                           amd64        OpenH264 library
ii  openh264-gst-plugins-bad-1.5:amd64     1.8.1-1kurento4.18.04                           amd64        GStreamer plugins from openh264
ii  openwebrtc-gst-plugins                 0.10.0-1kurento1.18.04                          amd64        OpenWebRTC specific GStreamer plugins
ii  openwebrtc-gst-plugins-dbg             0.10.0-1kurento1.18.04                          amd64        OpenWebRTC specific GStreamer plugins
root@kurento-online-hz-20200604002:/var/crash/1/
$
```

**Comment by j1elo** [comment]
Hi, we won't be able to look into all these crashes you are reporting, because vacations. Meanwhile you should fill up the section about how to reproduce, otherwise the stack trace is normally not enough info to find the cause of the crash. There is a lot of things to know, like what endpoints and filters you had running, how many, what kind of video was being sent (screen, webcam, 4K file) or recorded, the CPU and memory usage details of the machine (was it close to 100% usage?), and if possible even a small sample application that can be used to reproduce the issue. Thanks!

**Comment by darrenhp** [comment]
I'm sorry that I can't no reproduce it;
And our kms cluster has about 100+ instance；
The application is simple；most of over user are using webcam on pc/mac and limited to 640x480; 
Some users may use iphone/android； few users may share-screen, few rooms need to record audio; 

I think，if a  user can make it happen，the crash should occurr in many kms instances；(The user
retry/refresh the webrtc when the video is 'shutdown';)

And when the crash, the cpu(<10%)   and memory(<20%), tcp-connections(<150)  is in normal load;   
And there are 5 pipleline in the instance;  One pipeline acts like one-to-many, others acts like one-to-one;
