### ISSUE TITLE
Kurento media element Mixer doesn't work

### ISSUE THREAD

**Issue by YuryFokin** [Kurento/bugtracker#546]
## Prerequisites

* [x] I agree to fill this issue template.
* [x] I have read the [Troubleshooting Guide] and [Support Instructions].

[Troubleshooting Guide]: https://doc-kurento.readthedocs.io/en/latest/user/troubleshooting.html
[Support Instructions]: https://github.com/Kurento/.github/blob/master/SUPPORT.md

## Issue description
I am trying to use Kurento Mixer media element in server script (Node.js). Seems it doesn’t work at all. I get an error in the simplest example:
```
let kurentoClient = await kurento(urlKurentoServer);
let pipeline = await kurentoClient.create('MediaPipeline');
let mixer = await pipeline.create('Mixer');
let senderPort = await mixer.createHubPort();
let receiverPort = await mixer.createHubPort();
mixer.connect('AUDIO', senderPort, receiverPort);
```

Error example:
reconnect to server 0 100 7e9e4ed6-dceb-415f-9809-2fbfeb55e12e
 Invalid Session 
Trace: Error: Request has timed out

What’s wrong?

### INFO about Kurento Media Server

* Kurento version:  Kurento 6.14.0

**Comment by j1elo** [comment]
Not related to the Mixer; "reconnect to server" means that the JS client SDK cannot connect to the media server. First start from the hello-world tutorial, to confirm it works, and then work your way from there.

**Comment by YuryFokin** [comment]
Certainly JS client is connected with the server. I have working application and would like to try transfering from Composite element to Mixer element. Composite requires too much resources. But Mixer doesn't work.

**Comment by BarsAndCo** [comment]
I have the same problem. When i try to connect two hub by mixer then server crushes with timeout.
So this code:
console.log('11111')
await mixer.connect('AUDIO', sessionPresenter.hubPortSender, session.hubPortReceiver);
console.log('22222')

gives it:
11111
reconnect to server 0 100 710d3929-cac1-4a4d-9fa9-9269c03d9d75
Invalid Session
Trace: Error: Request has timed out
    at D:\Developer\Uni3dlabs\JS\mixer_server\node_modules\kurento-client\lib\KurentoClient.js:365:24
    at dispatchCallback (D:\Developer\mixer_server\node_modules\kurento-jsonrpc\lib\index.js:546:9)
    at Timeout.timeout (D:\Developer\mixer_server\node_modules\kurento-jsonrpc\lib\index.js:593:9)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  request: '{"jsonrpc":"2.0","method":"invoke","params":{"object":"8f46387c-3e11-40b2-a85d-cf01839eba0e_kurento.MediaPipeline/adba7dd5-ad65-42f6-b625-ed6d2c76bb11_kurento.Mixer","operation":"connect","operationParams":{"media":"AUDIO","source":"8f46387c-3e11-40b2-a85d-cf01839eba0e_kurento.MediaPipeline/adba7dd5-ad65-42f6-b625-ed6d2c76bb11_kurento.Mixer/cfd7cc09-eab1-4977-bca7-5295da7b7f2e_kurento.HubPort","sink":"8f46387c-3e11-40b2-a85d-cf01839eba0e_kurento.MediaPipeline/adba7dd5-ad65-42f6-b625-ed6d2c76bb11_kurento.Mixer/508decb7-bcc7-4f29-9f93-dff35d9f52be_kurento.HubPort"},"sessionId":"710d3929-cac1-4a4d-9fa9-9269c03d9d75"},"id":37}',
  retry: [Function: retry]
}
    at Object.noop (D:\Developer\mixer_server\node_modules\kurento-client-elements\lib\Mixer.js:35:22)
    at callback2 (D:\Developer\mixer_server\node_modules\promisecallback\index.js:27:25)
    at async handle_joinListener (file:///D:/Developer/mixer_server/server.js:235:5)
22222

**Comment by shaman79** [comment]
Hello, when is this going to be fixed? It is preventing us now from using Kurento. Thanks.
